export const LOADING_DIR = 'LOADING_DIR';
export const GET_DIRECTORIES = 'GET_DIRECTORIES';
export const LOADING_LOGIN = 'LOADING_LOGIN';
export const HANDLER_LOGIN = 'HANDLER_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
