export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const USER_AUTH = 'USER_AUTH';

export const GET_ERROR = 'GET_ERROR';

export const CREATE_DIRECTORY = 'CREATE_DIRECTORY';
export const ADD_DIRECTORY = 'ADD_DIRECTORY';
export const GET_DIRECTORIES = 'GET_DIRECTORIES';
export const GET_CURRENT_DIRECTORIES = 'GET_CURRENT_DIRECTORIES';
export const SET_DIRECTORIES = 'SET_DIRECTORIES';
export const SET_CURRENT_DIRECTORY = 'SET_CURRENT_DIRECTORY';
export const EDIT_DIRECTORY = 'EDIT_DIRECTORY';
export const TRY_DELETE_ITEM = 'TRY_DELETE_ITEM';
export const DELETE_DIRECTORY = 'DELETE_DIRECTORY';

export const ADD_BREADCRUMB_LINK = 'ADD_BREADCRUMB_LINK';
export const DELETE_BREADCRUMB_LINK = 'DELETE_BREADCRUMB_LINK';

export const SET_ISLASTDIR = 'SET_ISLASTDIR';

export const GET_CONTENT_CATEGORY = 'GET_CONTENT_CATEGORY';
export const SET_CONTENT_CATEGORY = 'SET_CONTENT_CATEGORY';

export const SET_THEME = 'SET_THEME';

export const UPDATE_COMPANY = 'UPDATE_COMPANY';
