export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const GET_ERROR = 'GET_ERROR';

export const CREATE_DIRECTORY = 'CREATE_DIRECTORY';
export const ADD_DIRECTORY = 'ADD_DIRECTORY';
export const GET_DIRECTORIES = 'GET_DIRECTORIES';
export const SET_DIRECTORIES = 'SET_DIRECTORIES';
